### ISSUE TITLE
警告：未经中央气象台允许在开源中面向大众公开资料，请立即删除，否者我们将追究责任人的一切法律责任

### ISSUE THREAD

**Issue by WeatherOfChina** [chn-lee-yumi/Satellite-Cloud-Image-WeixinAPP#1]
中央气象台（以下简称“本台”）作为国家级气象机构，面向公众发布权威气象信息，任何人不得通过非法手段获取本台任何信息，尤其是你方还将技术开源公布出来，严重侵犯本台正当权益，请你方立即删除与本台（www.nmc.cn）相关的技术代码，否者本台将有权利追究责任人的一切法律责任，请仔细阅读本台网站声明：http://www.nmc.cn/f/view/d994acb42d4b4bdf97034554499bb654/722665831f0a4e98800c41e691444963.html 。
获取数据请通过合法手段申请：http://data.cma.cn/

**Comment by chn-lee-yumi** [comment]
很抱歉现在才看到这个issue，我现在在旅游，无法使用电脑，所以我会在旅游回家后(2018年8月4日)立即删除与中央气象台相关的技术代码。

**Comment by chn-lee-yumi** [comment]
**我已删除贵台所有相关的技术代码。**
贵台特意注册了一个GitHub账号来这里给我警告，我受惊若宠。
我有三点想说的：
- 关于“任何人不得通过非法手段获取本台任何信息”，我通过浏览器的开发者工具找到FY4A图像列表接口网址，这个网址是写死在网页源文件上的，任何人都能看到，这算非法手段吗？
- 关于贵台网站声明中的"_任何媒体、网络或个人等第三方在未取得中央气象台书面授权的情况下，不得将中央气象台网站（www.nmc.cn）范围内的任何内容以任何方式（包括但不限于转载、链接、转帖或复制发表）**用于商业或者其他不合法用途**_"，我这个小程序目的是为公众提供一个方便的查看卫星云图的途径，显然不是商业用途，但这是不合法用途吗？
- 台湾交通部中央气象局的资料无需授权即允许公众“_不限時間及地域，重製、改作、編輯、公開傳輸或為其他方式之利用，開發各種產品或服務_”（ https://www.cwb.gov.tw/V7/information.htm ）我不明白为何中央气象台不可以。
