### ISSUE TITLE
希望作者继续维护此项目

### ISSUE THREAD

**Issue by yuwan-jpg** [chn-lee-yumi/Satellite-Cloud-Image-WeixinAPP#4]

**Comment by chn-lee-yumi** [comment]
个人开发者的小程序不允许有视频，不然过不了审核，我也没啥办法……除非把视频功能去掉。

**Comment by yuwan-jpg** [comment]
> 个人开发者的小程序不允许有视频，不然过不了审核，我也没啥办法……除非把视频功能去掉。

微信小程序审核机制真的奇怪，我用了你项目加上这个卫星云图视频功能；第一次审核竟然过了，第二次再提交就过不了
![](https://s3.bmp.ovh/imgs/2022/07/08/b66b1b373c43f2d3.jpg)

**Comment by plaidwork** [comment]
审核人员不一样有些严格一些，但大部分都不会给过🤪

**Comment by chn-lee-yumi** [comment]
> 微信小程序审核机制真的奇怪，我用了你项目加上这个卫星云图视频功能；第一次审核竟然过了，第二次再提交就过不了

然后你的小程序就只能卡住当前版本了2333

**Comment by yuwan-jpg** [comment]
> > 微信小程序审核机制真的奇怪，我用了你项目加上这个卫星云图视频功能；第一次审核竟然过了，第二次再提交就过不了
> 
> 然后你的小程序就只能卡住当前版本了2333

我已经审核过了几个版本了，偶尔会有一次过不了审；可能是审核员意见不统一的原因。
注意小程序里不要带有视频的字样，video组件加个自动播放的属性autoplay="true"；因为这样看起来是一张图，隐藏控制组件最好。加一个服务类目工具 > 图片处理

**Comment by chn-lee-yumi** [comment]
> 注意小程序里不要带有视频的字样，video组件加个自动播放的属性autoplay="true"；因为这样看起来是一张图，隐藏控制组件最好。加一个服务类目工具 > 图片处理

学会了，我刚刚也在想，因为审核不会看源码，所以我可以弄个开关（比如数据库里面写个值，小程序打开这个页面就读库判断是否显示视频），审核的时候看到的是图，审核过了之后再放出来视频。

**Comment by chn-lee-yumi** [comment]
突然发现腾讯开始割韭菜了……云开发现在没免费版了

**Comment by chn-lee-yumi** [comment]
新版本已发布，谢谢大家~
